"""
music_spectrum.py

Direction-of-arrival (DOA) estimation using the MUSIC algorithm.

MUSIC (MUltiple SIgnal Classification) is a subspace-based estimator that
exploits a fundamental property of the array covariance matrix:

    The steering vector a(θ) of a TRUE source is ORTHOGONAL to the noise
    subspace eigenvectors of R = E[x·x^H].

Scanning a(θ) across all angles and measuring how close it gets to orthogonal
with the noise subspace produces a pseudospectrum with sharp peaks exactly at
the source directions.

Algorithm
---------
  1. Compute sample covariance  R = (1/N) X X^H        (4×4 matrix)
  2. Eigendecompose  R = E Λ E^H                        (ascending λ order)
  3. Extract noise subspace  E_noise = E[:, :n_noise]   (2 smallest eigenvectors)
  4. For each scan angle θ:  P(θ) = 1 / ‖E_noise^H a(θ)‖²
  5. Peaks in P(θ) → estimated DOA angles
  6. Plot spatial spectrum + eigenvalue diagram

Input  : array_data.npy    (generated by generate_array_data.py)
Output : music_spectrum.png
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D
from scipy.linalg import eigh
from scipy.signal import find_peaks


def music_spectrum(
    data_file:  str         = "array_data.npy",
    n_signals:  int         = 2,                        # GPS + jammer
    f_carrier:  float       = 1575.42e6,                # GPS L1, Hz
    theta_scan: np.ndarray  = np.linspace(-90, 90, 3601),  # 0.05° resolution
    save_fig:   str         = "music_spectrum.png",
) -> np.ndarray:
    """
    Estimate direction-of-arrival using MUSIC and produce a 2-panel plot.

    Panel 1: MUSIC pseudospectrum (dB) vs angle — peaks at source directions.
    Panel 2: Covariance eigenvalues — shows signal/noise subspace split.

    Parameters
    ----------
    data_file  : path to the complex IQ array data (.npy)
    n_signals  : number of sources (must be < n_elements)
    f_carrier  : GPS L1 frequency used to compute steering vectors
    theta_scan : angles (degrees) over which to evaluate the spectrum
    save_fig   : output filename for the saved figure

    Returns
    -------
    spectrum_db : np.ndarray, shape (len(theta_scan),)
        Normalised MUSIC pseudospectrum in dB (maximum = 0 dB).
    """

    # ==================================================================
    # 1. LOAD DATA AND COMPUTE THE SAMPLE COVARIANCE MATRIX
    # ==================================================================

    X = np.load(data_file)                        # shape (n_elements, n_samples)
    n_elements, n_samples = X.shape

    # Sample covariance matrix: R̂ = (1/N) · X · X^H
    #
    # R̂ is n_elements × n_elements = 4×4, Hermitian, positive semi-definite.
    # Each entry R̂[m, k] = (1/N) Σ_t x_m(t) · x_k*(t) is the time-averaged
    # cross-correlation between antenna m and antenna k.
    #
    # For our two-source scenario, R̂ has the approximate structure:
    #   R̂ ≈ P_gps · a_gps·a_gps^H  +  P_jam · a_jam·a_jam^H  +  σ²·I
    # where P_gps, P_jam are signal powers and σ² is the noise power per element.
    R = (X @ X.conj().T) / n_samples              # shape (4, 4), complex128
    #   @ = matrix multiply    .conj().T = conjugate transpose (Hermitian adjoint)

    # ==================================================================
    # 2. EIGENDECOMPOSE R  →  SIGNAL + NOISE SUBSPACES
    # ==================================================================

    # scipy.linalg.eigh: eigendecomposition for HERMITIAN matrices.
    # Advantages over np.linalg.eig:
    #   - Guaranteed real eigenvalues (exploits Hermitian structure)
    #   - Ascending order by default — convenient for subspace split
    #   - Numerically more stable (uses divide-and-conquer algorithm)
    eigenvalues, eigenvectors = eigh(R)
    # eigenvalues  : shape (4,),  real, ASCENDING order (smallest first)
    # eigenvectors : shape (4,4), columns are orthonormal eigenvectors

    # --- Subspace split ---
    # With n_signals sources and n_elements antennas:
    #   Noise subspace  : n_noise = n_elements - n_signals = 2 eigenvectors
    #   Signal subspace : n_signals = 2 eigenvectors
    #
    # The two sources inject power into R along their steering vectors,
    # creating two eigenvalues much larger than the noise floor σ².
    # The remaining n_noise eigenvalues equal σ² (thermal noise only).
    n_noise = n_elements - n_signals                # = 2
    E_noise = eigenvectors[:, :n_noise]             # shape (4, 2) — noise subspace

    # ==================================================================
    # 3. ARRAY GEOMETRY  (identical to generate_array_data.py)
    # ==================================================================

    c   = 3e8                                       # speed of light, m/s
    lam = c / f_carrier                             # GPS L1 wavelength ≈ 0.190 m
    d   = lam / 2                                   # half-wavelength spacing ≈ 0.095 m

    def steering_vector(theta_deg: float) -> np.ndarray:
        """
        ULA steering vector for a plane wave arriving from theta_deg.

        CRITICAL: This function must be byte-for-byte identical to the one in
        generate_array_data.py.  MUSIC works by comparing a(θ) against the
        eigenvectors of R; any mismatch in array geometry breaks the orthogonality
        and produces wrong or missing peaks.
        """
        theta = np.deg2rad(theta_deg)
        m     = np.arange(n_elements)              # [0, 1, 2, 3]
        phase = (2 * np.pi / lam) * d * m * np.sin(theta)
        return np.exp(1j * phase)                  # shape (4,)

    # ==================================================================
    # 4. MUSIC PSEUDOSPECTRUM SCAN
    # ==================================================================

    spectrum = np.zeros(len(theta_scan))

    for i, theta in enumerate(theta_scan):
        a = steering_vector(theta)                 # candidate steering vector, (4,)

        # Project a onto the noise subspace:
        #   proj = E_noise^H · a   →   shape (2,)
        #
        # Physical meaning: how much of a(θ) "points into" the noise subspace?
        # If θ is a real source direction, a(θ) lies in the SIGNAL subspace,
        # which is orthogonal to the noise subspace by construction → proj ≈ 0.
        proj  = E_noise.conj().T @ a               # (2,2)^H × (4,) = wait, (2,4)×(4,) = (2,)

        # ‖proj‖² = proj^H · proj = real scalar  (Hermitian inner product)
        denom = np.real(np.dot(proj.conj(), proj))

        # MUSIC pseudospectrum: peaks where denom → 0
        # +1e-12 prevents division by zero at exact source angles
        spectrum[i] = 1.0 / (denom + 1e-12)

    # Normalise to maximum = 1, then express in dB
    # (0 dB = peak, negative dB = everything else)
    spectrum_db = 10 * np.log10(spectrum / spectrum.max())

    # ==================================================================
    # 5. PEAK FINDING  →  ESTIMATED DOA ANGLES
    # ==================================================================

    # A genuine peak must be:
    #   - Within 35 dB of the global maximum
    #   - At least 5° away from any other peak (avoids sidelobes)
    #
    # Why 35 dB?  The GPS signal is 30 dB BELOW the jammer (SNR = 0 dB vs noise,
    # but 30 dB below jammer).  In the MUSIC spectrum, the GPS peak appears at
    # roughly -(10·log10(λ_jam / λ_GPS)) dB ≈ -(10·log10(4006/4.76)) ≈ -29 dB
    # relative to the jammer peak.  A -35 dB threshold captures it cleanly
    # while rejecting the sidelobe floor at < -50 dB.
    deg_per_bin  = theta_scan[1] - theta_scan[0]   # 0.05°/bin
    min_sep_bins = int(5.0 / deg_per_bin)           # 5° in bins = 100 bins

    peaks_idx, _ = find_peaks(
        spectrum_db,
        height   = -35,           # within 35 dB of maximum — captures weak GPS peak
        distance = min_sep_bins,  # minimum separation between peaks
    )
    peak_angles = theta_scan[peaks_idx]

    # ==================================================================
    # 6. PRINT RESULTS
    # ==================================================================

    print("=" * 55)
    print("MUSIC  —  direction-of-arrival estimation")
    print("=" * 55)
    print(f"  n_elements            : {n_elements}")
    print(f"  n_samples             : {n_samples}")
    print(f"  Eigenvalues (ascend.) : {np.round(eigenvalues.real, 1)}")
    print(f"  Noise subspace λ avg  : {eigenvalues.real[:n_noise].mean():.2f}  (≈ σ²)")
    print(f"  Signal subspace λ     : {np.round(eigenvalues.real[n_noise:], 1)}")
    print(f"  Estimated DOA angles  : {np.round(peak_angles, 2)}°")
    print(f"  Ground truth          : GPS = 0.0°,  Jammer = 45.0°")
    errors = peak_angles - np.array([0.0, 45.0])[:len(peak_angles)]
    print(f"  Errors                : {np.round(errors, 2)}°")

    # ==================================================================
    # 7. PUBLICATION-QUALITY PLOT
    # ==================================================================

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle(
        "MUSIC Direction-of-Arrival Estimation  |  4-Element ULA, GPS L1 (1575.42 MHz)",
        fontsize=13, fontweight='bold'
    )

    # ---- Panel 1: Spatial Spectrum ----------------------------------------

    ax1.plot(theta_scan, spectrum_db,
             color='royalblue', linewidth=1.5, zorder=3)

    # Shade area under each detected peak
    for ang in peak_angles:
        mask = np.abs(theta_scan - ang) < 5
        ax1.fill_between(theta_scan[mask], -50, spectrum_db[mask],
                         alpha=0.15, color='darkorange')

    # Ground truth vertical lines
    ax1.axvline(0,  color='limegreen', linestyle='--', linewidth=2.0, zorder=4)
    ax1.axvline(45, color='tomato',    linestyle='--', linewidth=2.0, zorder=4)

    # Detected peak vertical lines (dotted orange)
    for ang in peak_angles:
        ax1.axvline(ang, color='darkorange', linestyle=':', linewidth=2.5, zorder=5)

    # Annotate peaks with angle labels
    for ang in peak_angles:
        y_pos = spectrum_db[np.argmin(np.abs(theta_scan - ang))]
        ax1.annotate(f'{ang:.1f}°',
                     xy=(ang, y_pos),
                     xytext=(ang + 4, y_pos - 5),
                     fontsize=10, color='darkorange', fontweight='bold',
                     arrowprops=dict(arrowstyle='->', color='darkorange', lw=1.2))

    # Build legend manually for cleanliness
    legend_handles = [
        Line2D([0], [0], color='royalblue',   lw=1.5,                label='MUSIC pseudospectrum'),
        Line2D([0], [0], color='limegreen',   lw=2.0, linestyle='--', label='GPS truth (0°)'),
        Line2D([0], [0], color='tomato',      lw=2.0, linestyle='--', label='Jammer truth (45°)'),
        Line2D([0], [0], color='darkorange',  lw=2.0, linestyle=':',  label=f'Detected peaks: {np.round(peak_angles, 1)}°'),
    ]
    ax1.legend(handles=legend_handles, fontsize=9, loc='lower right')
    ax1.set_xlabel("Angle of Arrival (degrees)", fontsize=12)
    ax1.set_ylabel("MUSIC Pseudospectrum (dB)", fontsize=12)
    ax1.set_title("Spatial Spectrum", fontsize=12)
    ax1.set_xlim(-90, 90)
    ax1.set_ylim(-50, 3)
    ax1.set_xticks(np.arange(-90, 91, 15))
    ax1.grid(True, alpha=0.3)

    # ---- Panel 2: Eigenvalue Diagram ----------------------------------------

    # Sort descending so λ₁ (largest = jammer) is on the left
    sorted_ev = np.sort(eigenvalues.real)[::-1]
    ev_colors = ['royalblue'] * n_signals + ['tomato'] * n_noise
    # In descending order: first n_signals are signal, last n_noise are noise

    bars = ax2.bar(
        np.arange(1, n_elements + 1), sorted_ev,
        color=ev_colors, edgecolor='black', linewidth=0.8, zorder=3,
        width=0.55
    )

    # Log scale so all four bars are visible — jammer at 4006, noise at ~1
    ax2.set_yscale('log')

    # Noise floor reference line (mean of the two smallest eigenvalues)
    noise_floor = eigenvalues.real[:n_noise].mean()
    ax2.axhline(noise_floor, color='gray', linestyle=':', linewidth=1.5,
                label=f'Noise floor = {noise_floor:.2f}')

    # Annotate each bar with its value
    for bar, val in zip(bars, sorted_ev):
        label = f'{val:.0f}' if val >= 10 else f'{val:.2f}'
        ax2.text(
            bar.get_x() + bar.get_width() / 2,
            val * 1.4,
            label,
            ha='center', va='bottom', fontsize=10, fontweight='bold'
        )

    # Bracket showing the signal/noise subspace boundary
    ax2.axvline(n_signals + 0.5, color='black', linestyle='-', linewidth=1.2,
                alpha=0.4)
    ax2.text(n_signals + 0.55, noise_floor * 3,
             '← signal | noise →', fontsize=8.5, va='center',
             color='dimgray', style='italic')

    # Legend
    sig_patch   = mpatches.Patch(color='royalblue', label=f'Signal eigenvectors ({n_signals})')
    noise_patch = mpatches.Patch(color='tomato',    label=f'Noise eigenvectors ({n_noise})')
    noise_line  = Line2D([0], [0], color='gray', linestyle=':', lw=1.5,
                         label=f'Noise floor = {noise_floor:.2f}')
    ax2.legend(handles=[sig_patch, noise_patch, noise_line], fontsize=9)

    ax2.set_xlabel("Eigenvalue Index (1 = largest)", fontsize=12)
    ax2.set_ylabel("Eigenvalue Magnitude", fontsize=12)
    ax2.set_title("Covariance Matrix Eigenvalues\n(Signal vs. Noise Subspace)", fontsize=12)
    ax2.set_xticks(np.arange(1, n_elements + 1))
    ax2.set_xticklabels([f"λ{i}" for i in range(1, n_elements + 1)], fontsize=11)
    ax2.grid(True, axis='y', alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_fig, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"\n  Saved plot : {save_fig}")

    return spectrum_db


# ======================================================================
# QUICK RUN  —  python music_spectrum.py
# ======================================================================
if __name__ == "__main__":
    music_spectrum()
